### ISSUE TITLE
Cannot get this to work on create-react-app

### ISSUE THREAD

**Issue by thtliife** [1egoman/backstroke#52] opened 2017-02-12 23:23 UTC
Has anyone successfully gotten this to work with a fork of https://github.com/facebookincubator/create-react-app ?

I cannot get it to work in either the standard or classic setup.

In standard mode, I get the following error when trying to save a link:
`No permission to add a webhook to the repository facebookincubator/create-react-app. Make sure thtliife has given Backstroke permission to access this organisation or repo via OAuth.`

![screen shot 2017-02-13 at 9 10 31 am](https://cloud.githubusercontent.com/assets/9210782/22867143/f9df5a92-f1cd-11e6-8382-a94442c620cd.png)

In classic mode, I get the following response...
```json
Uhh, error: {
	"message": "Validation Failed",
	"errors": [{
		"message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",
		"resource": "Search",
		"field": "q",
		"code": "invalid"
	}],
	"documentation_url": "https://developer.github.com/v3/search/"
}
```

Any ideas what I am doing wrong?

The create-react-app is not a private repo, as per https://github.com/facebookincubator/create-react-app/issues/1545#issuecomment-279257950

**Comment by 1egoman** [comment] 2017-02-13 00:17
I recently discovered a bug in Backstroke, and this issue looks to be caused by it. Basically, if a source repository is not able to be written to by the user creating the Backstroke link, creating the link fails with that error that you've specified.

I've had the fix in a [pull request](https://github.com/1egoman/backstroke/pull/51) while validating it, but I'm pretty sure it works at this point.

Here's an example link I've created:
<img width="1190" alt="screen shot 2017-02-12 at 6 47 18 pm" src="https://cloud.githubusercontent.com/assets/1704236/22867298/c09c369e-f153-11e6-910d-083f2cef0048.png">

Can you confirm this fixes the issue?

I read the linked issue on create-react-app, and posted a comment on there as well. I'm going to try and clean up the documentation tonight and make it more clear how to set up and use Backstroke on a repository.

**Comment by thtliife** [comment] 2017-02-13 00:27
Hi @1egoman it looks to be ok now :)
I can successfully create a link on https://backstroke.us
and testing with curl returns
```json
{
	"status": "ok",
	"output": {
		"status": "ok",
		"pullRequest": {
			"msg": "There's already a pull request for this repo, no need to create another."
		},
		"isEnabled": true,
		"many": false,
		"forkCount": 1
	}
}
```

Thanks for the __fast__ bug fix :)

**Comment by 1egoman** [comment] 2017-02-13 00:48
I think this has been fixed, so I'm going to close this issue. If I missed something, let me know and I'll reopen.

**Closed by 1egoman** 2017-02-13 00:48 UTC

**Comment by thtliife** [comment] 2017-02-13 02:27
seems fixed to me :)
Ill come back and let you know if something doesn't work on their next push, but quietly confident that won't be necessary :)

**Comment by gaearon** [comment] 2017-02-13 15:49
Thank you so much for the fix.
